In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("/workspaces/ERP_Newsletter/data/data05_full_articles_selected/govuk_dfe_articles_2023_2025.csv")

In [4]:
df.head()

,url,title,from,date,text
0,https://www.gov.uk/government/publications/not...,Notice to improve: Sikh Academies Trust,Department for Education,2024-11-15,A notice to improve issued to Sikh Academies T...
1,https://www.gov.uk/government/news/new-qualifi...,New qualifications to tackle NHS skills shortage,Skills England,2025-12-12,"New qualifications in MedTech to tackle 145,00..."
2,https://www.gov.uk/government/news/3bn-investm...,£3bn investment to end postcode lottery for ch...,Department for Education; The Rt Hon Bridget P...,2025-12-11,"Around 50,000 specialist places to be created ..."
3,https://www.gov.uk/government/publications/res...,Response to Secretary of State steer letter,Ofqual,2025-12-11,A letter to the Secretary of State from Sir Ia...
4,https://www.gov.uk/government/publications/on-...,On-screen exams: Education Secretary writes to...,Department for Education,2025-12-11,"Education Secretary, Bridget Phillipson, write..."

In [6]:
df["from"].value_counts()

from
Education and Skills Funding Agency                                                                               118
Student Loans Company                                                                                              88
Department for Education                                                                                           87
Department for Education; The Rt Hon Bridget Phillipson MP                                                         71
Regional Department for Education (DfE) Directors                                                                  63
                                                                                                                 ...
Ofsted; Victoria and Albert Museum; Amanda Spielman                                                                 1
Nuclear Waste Services                                                                                              1
Department for Education; Department of Health and Social Care; The Rt Hon Claire Coutinho MP; Neil O'Brien MP      1
Department for Education; The Rt Hon Robert Halfon; The Rt Hon Gillian Keegan                                       1
Ofqual; Sir Ian Bauckham CBE                                                                                        1
Name: count, Length: 214, dtype: int64

In [7]:
df["from"].nunique()

214

In [8]:
df["from"].value_counts().reset_index(name="count").rename(
    columns={"index": "from"}
)

                                                  from  count
0                  Education and Skills Funding Agency    118
1                                Student Loans Company     88
2                             Department for Education     87
3    Department for Education; The Rt Hon Bridget P...     71
4    Regional Department for Education (DfE) Directors     63
..                                                 ...    ...
209  Ofsted; Victoria and Albert Museum; Amanda Spi...      1
210                             Nuclear Waste Services      1
211  Department for Education; Department of Health...      1
212  Department for Education; The Rt Hon Robert Ha...      1
213                       Ofqual; Sir Ian Bauckham CBE      1

[214 rows x 2 columns]

In [9]:
df["from"].value_counts().reset_index(name="count").to_csv(
    "from_value_counts.csv", index=False
)